# netlify.toml

# Specify build settings
[build]
  command = ""  # No build command as there's no build step
  functions = ""  # No separate functions directory

# Specify redirect rules for routing
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/authRoutes/:splat"
  status = 200

[[redirects]]
  from = "/geospatial/*"
  to = "/.netlify/functions/geospatialRoutes/:splat"
  status = 200

# Optional: Configure headers for CORS if needed
[[headers]]
  for = "/auth/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/geospatial/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type"
